---
openapi: 3.0.1
info:
  title: OneApp Payment API
  version: v1
tags:
- name: Users
  description: User management
- name: Doctors
  description: Doctor management
- name: Patients
  description: Patient management
- name: Invoices
  description: Invoice management
paths:
  "/api/v1/doctors":
    get:
      summary: list doctors
      tags:
      - Doctors
      responses:
        '200':
          description: successful
  "/api/v1/doctors/{id}":
    get:
      summary: show doctor
      tags:
      - Doctors
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: found
    patch:
      summary: update doctor
      tags:
      - Doctors
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
  "/api/v1/invoices":
    get:
      summary: list invoices
      tags:
      - Invoices
      responses:
        '200':
          description: successful
    post:
      summary: create invoice
      tags:
      - Invoices
      parameters: []
      responses:
        '201':
          description: created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doctor_id:
                  type: integer
                patient_id:
                  type: integer
                service_name:
                  type: string
                amount:
                  type: number
                discount:
                  type: number
                tax:
                  type: number
                payment_method:
                  type: string
                status:
                  type: string
                conversion_rate:
                  type: number
                blockchain_network:
                  type: integer
                sender_wallet_address:
                  type: string
                receiver_wallet_address:
                  type: string
              required:
              - doctor_id
              - patient_id
              - service_name
              - amount
  "/api/v1/invoices/{id}":
    get:
      summary: show invoice
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: found
    patch:
      summary: update invoice
      tags:
      - Invoices
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                solana_signature:
                  type: string
  "/api/v1/doctors/{doctor_id}/patients":
    get:
      summary: list patients
      tags:
      - Patients
      responses:
        '200':
          description: successful
    post:
      summary: create patient
      tags:
      - Patients
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    phone_number:
                      type: string
                  required:
                  - first_name
                  - last_name
                  - phone_number
  "/api/v1/doctors/{doctor_id}/patients/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    get:
      summary: show patient
      tags:
      - Patients
      responses:
        '200':
          description: successful
    put:
      summary: update patient
      tags:
      - Patients
      parameters: []
      responses:
        '200':
          description: updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                patient:
                  type: object
                  properties:
                    first_name:
                      type: string
                    last_name:
                      type: string
                    phone_number:
                      type: string
    delete:
      summary: delete patient
      tags:
      - Patients
      responses:
        '204':
          description: deleted
  "/api/v1/users":
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - user
              properties:
                user:
                  type: object
                  required:
                  - email
                  - password
                  - password_confirmation
                  - user_role
                  properties:
                    email:
                      type: string
                      format: email
                    password:
                      type: string
                      format: password
                    password_confirmation:
                      type: string
                      format: password
                    user_role:
                      type: string
                      enum:
                      - doctor
                      - patient
                  oneOf:
                  - required:
                    - doctor_attributes
                    properties:
                      doctor_attributes:
                        type: object
                        required:
                        - first_name
                        - last_name
                        - phone
                        - license_number
                        properties:
                          first_name:
                            type: string
                          last_name:
                            type: string
                          email:
                            type: string
                          phone:
                            type: string
                          specialty:
                            type: string
                          license_number:
                            type: string
                          clinic_name:
                            type: string
                          clinic_address:
                            type: string
                          location:
                            type: string
                          profile_picture:
                            type: string
                            format: binary
                  - required:
                    - patient_attributes
                    properties:
                      patient_attributes:
                        type: object
                        required:
                        - first_name
                        - last_name
                        - phone_number
                        - dob
                        properties:
                          first_name:
                            type: string
                          last_name:
                            type: string
                          phone_number:
                            type: string
                          dob:
                            type: string
                            format: date
servers:
- url: http://localhost:3000
  description: Local server
